CREATE TABLE users (
    id SERIAL NOT NULL,
    username CHARACTER VARYING(20) UNIQUE NOT NULL,
    email VARCHAR(20) UNIQUE NOT NULL,
    address VARCHAR(20) UNIQUE INDEX NOT NULL,
    CONSTRAINT users_id PRIMARY KEY (id)
);
